### ISSUE TITLE
issue: omada access-point incompatible with EAP245 ?

### ISSUE THREAD

**Issue by FlyingToto** [MarkGodwin/tplink-omada-api#50]
just an FYI, that there is an error when trying to execute omada access-point against an older access point EAP245(US) v3.0:
it works find with EAP773(US) v1.0

notes: 

- there are no VLAN configured in this case, 
- the eap245 uses the same site-wide-default configuration as the other access points.
- other commands seem to work fine with the EAP245... 

```
ff@hal:~/naxdev/logs$ omada access-point wee_wifi
Name: wee_wifi
Address: AA-BB-CC-DD-EE-FF (192.168.0.212)
Status: CONNECTED (CONNECTED)
LAN Ports: 1
Traceback (most recent call last):
  File "/home/ff/.local/bin/omada", line 8, in <module>
    sys.exit(main())
  File "/home/ff/.local/lib/python3.10/site-packages/tplink_omada_client/cli/__init__.py", line 74, in main
    return asyncio.run(args.func(vars(args)))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ff/.local/lib/python3.10/site-packages/tplink_omada_client/cli/command_access_point.py", line 22, in command_access_point
    print(f"   Port {p.port_name}  PoE Supported: {get_checkbox_char(p.supports_poe)} {get_power_char(p.poe_enable)}  Vlan: {get_checkbox_char(p.supports_vlan and p.local_vlan_enable)} {p.local_vlan_id}")
  File "/home/ff/.local/lib/python3.10/site-packages/tplink_omada_client/devices.py", line 371, in local_vlan_id
    return self._data["localVlanId"]
KeyError: 'localVlanId'
```

**Comment by MarkGodwin** [comment]
This should be fixed in the version 1.4.1. Please give it a try and let me know.
